apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agent-api
  labels:
    app: ai-agent-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-agent-api
  template:
    metadata:
      labels:
        app: ai-agent-api
    spec:
      containers:
        - name: api
          image: your-dockerhub-username/ai-agent-api:latest  # replace with your image
          ports:
            - containerPort: 8000
          env:
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ai-agent-secrets
                  key: telegram_bot_token
            - name: TELEGRAM_BOT_NAME
              valueFrom:
                secretKeyRef:
                  name: ai-agent-secrets
                  key: telegram_bot_name
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ai-agent-secrets
                  key: slack_bot_token
            - name: SLACK_TEAM_ID
              valueFrom:
                secretKeyRef:
                  name: ai-agent-secrets
                  key: slack_team_id
            - name: NOTION_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ai-agent-secrets
                  key: notion_api_token
            - name: TOGETHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-agent-secrets
                  key: together_api_key
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-agent-secrets
                  key: google_api_key
          volumeMounts:
            - name: uploads
              mountPath: /app/data/uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads-pvc
