apiVersion: v1
kind: Service
metadata:
  name: ai-agent-api-service
spec:
  selector:
    app: ai-agent-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer  # or NodePort for local clusters
